### PR TITLE
1224977 aws maxlen

### PR DESCRIPTION
**Pull request by dunnill**
##### Corresponding Issue(s):
 - PRs should have a corresponding issue. If no issue exists, provide details in the **Reason for Change(s)** section

##### Summary of change(s):
Enable max length of cluster to be variable.
##### Reason for Change(s):
- If a bug, describe error scenario, including expected behavior and actual behavior.

- If an enhancement, describe the use case and the perceived benefit(s).
Avoid custom module due to desire to increase this to 40.  Default is still 20 to minimise impact to customer who don't want this feature added.

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:
No - unless maxlen is set to not be 20

##### If input variables or output variables have changed or has been added, have you updated the README?
Yes

##### Do examples need to be updated based on changes?
No - impact on cluster naming only

##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

### CODE REVIEW

**Comment by dunnill** [comment]
@bohn002 Just curious why truncated name is maxed at 20?  It's causing rebuild on my example as it has 21 characters but 40 are permitted.  It was why I used a var initially so that any existing stack with any specific limit can be imported and not recreated.

**Comment by bohn002** [comment]
@dunnill The way the module was built, back when the name limit was 20 characters, truncated name is used to shave down the names if it was more than 20 characters because of the character limit. That truncated name variable is used for both the cluster name and the `replication_group_id`. 

Now that the character limit has been raised to 50 for the name the new problem is that `replication_group_id` has a max of 40 characters in it. So by bumping the numbers from 19/20 to 49/50 we are forcing rebuilds since its a calculated field. We were avoiding the variable solution since it appears as though its an arbitrary limit and not a hard limit. Additionally, if you set the limit to 50 characters, which is valid for the name, you would run into errors with `replication_group_id`.

Additionally, we don't import resources through the typical use of the modules. They are already existing in state, and through upgrading the module, we would have to make sure there is guidance for support so they can pull the cluster names, count the characters and then update the variables all before they submit the changes.

So once we make sure the changes are backwards compatible, or docs around how to mitigate changes we can get things added.

**Comment by dunnill** [comment]
Ah thanks, glad you took this one as I forgot that little nugget!  Also - looks sweet to me.  Not sure who does the approvals but that will work super!  Much appreciated.

**Comment by dunnill** [comment]
Darn, just re-ran it and it's gotten less happy!  I've moved to using cluster/replication name but the name is "dv1-beehive-redis-v00" yet the param group (subnets etc too) changes "dv1-beehive-redis-ecparamgroup" -> "dv1-beehive-redis-v00-ecparamgroup".   But then again, would it regenerate elasticache anyway as dv1-beehive-redis-v00 is no longer generated but specified by the new params?

**Comment by bohn002** [comment]
Hi @dunnill still working on the PR, we are deprecating the `name` and `version_name` fields and introducing `cluster_name` and `replication_group_name` fields. We are making sure that if you use the previous 2 fields, everything works the same (stilling testing that), and if you want more than 20 characters you need to not use name/version_name but cluster_name/replication_group_name". You can also migrate to the new standard by taking your existing cluster name and group id and inserting them into `cluster_name` and `replication_group_name` and it should not prompt a rebuild, something else we are retesting. 

Again, still testing backwards compatibility and adding automated testing as well so soon two of my compatriots will reiew and approve the PR.

**Comment by dunnill** [comment]
Hmm, maybe the effects are less far reaching or maybe I got lucky as I am creating Redis cluster as I've tweaked the values so they differ (almost as I suggested above) and now it's much happier.  6 in place updates due to cluster being renamed without v00, much better than 10 create/destroys, as replication_name is keeping v00.  Much saner.  👍

**Review by johnctitus — DISMISSED** [review]

**Review by gdelvalle — APPROVED** [review]

**Review by johnctitus — APPROVED** [review]

**Review by gdelvalle — APPROVED** [review]

**Pull request merged**
